services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ../data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_catalogue
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      CONVERSION_API_URL: ${CONVERSION_API_URL}
      SPRING_CACHE_TYPE: ${SPRING_CACHE_TYPE}
      SPRING_CACHE_CAFFEINE_SPEC: ${SPRING_CACHE_CAFFEINE_SPEC}
    ports:
      - "8005:8005"
    depends_on:
      - postgres
    env_file:
      - .env